#!/usr/bin/env bash
set -u

# takes in a list of URLs, optionally with date (in csv with dumb seperator ¤)
# outputs .eml files that can be mass-imported by Thunderbird ImportExportTools NG
# use: RSS feeds only offer last n entries; getting URLs for all entries manually is usually quick and easy*, so this is a method to complete the feed listing in TB.
# * except for pagination, in which case parsehub is painfully used due to no better working alternative

# from https://unix.stackexchange.com/a/7012/389250

case "$#" in
	0)
		read -rp 'Directory to save files: ' filesdirectory # where are we doing stuff?
		;;
	1)
		filesdirectory="$1"
		;;
	*)
		echo "Up to 1 arguments expected, got $?"
		echo "Usage: email-me-links [output_directory]"
		;;
esac
mkdir -p "$filesdirectory"

echo "1st: date, 2nd: url; OR 1st: url"
echo "seperator is ¤"
touch "$filesdirectory/.index" # get urls
$EDITOR "$filesdirectory/.index"

first="$(head -n1 "$filesdirectory/.index")"
url="$(cut -d¤ -f2 <<< "$first")"
if [[ "$url" == "" ]]; then
	url="$(cut -d¤ -f1 <<< "$first")"
else
	date="$(cut -d¤ -f1 <<< "$first")"
        echo "first date: $(date -R -u -d "$date")"
fi
title="$(curl -sL "$url" | htmlq -t title)"
echo "Title of first is: ${title}"
IFS= read -rp 'String to remove from beginning of title: ' removeprefix
IFS= read -rp 'String to remove from end of title: ' removesuffix
unset date url

counter=0
while IFS="¤" read -r date url; do
	((counter++))
	if [[ "$url" == ""  ]]; then # no date, only url (1st field)
		url="$date"
		date="Thu, 01 Jan 1970 00:00:01 +0000"
	fi

	from=$(echo "$url" | sed -e "s/[^/]*\/\/\([^@]*@\)\?\([^:/]*\).*/\2/") # domain part

  pagetitle="$(curl -sL "$url" | htmlq -t title)"
	pagetitle="${pagetitle#"${removeprefix}"}"
	pagetitle="${pagetitle%"${removesuffix}"}"

	date="$(date -R -u -d "$date")"
	{
	echo "From: $from"
	echo "MIME-Version: 1.0"
	echo "Subject: $pagetitle"
	echo "Content-Transfer-Encoding: 8bit"
	echo "Content-Base: $url" # shows up as website in Thunderbird
	echo 'Content-Type: text/html; charset=UTF-8'
	echo "Date: $date"
	} > "$filesdirectory/$counter.eml"
done < "$filesdirectory/.index"
