#!/usr/bin/env bash
set -eo pipefail

if [[ "$#" -lt 3 ]]; then
	echo "error: expected at least 3 args"
	echo "USAGE: ffmpeg-join <input...> <output>"
	exit 1
fi

temp="$(mktemp)"

for arg in "$@"; do
    echo "file $(realpath "$arg")" >> "$temp"
done

lastarg="$(tail -n1 "$temp" | cut -d' ' -f2)" # file <arg> to <arg>
sed -i '$d' "$temp"

ffmpeg -hide_banner -loglevel warning -f concat -safe 0 -i "$temp" -c copy "$lastarg"
