#!/usr/bin/env bash
set -eo pipefail

if [[ "$#" != 2 ]]; then
	echo "USAGE: <file/dir> <startTrimSeconds>"
	exit 1
fi

function one {
	jas="$(dirname "$1")/jas_$(basename "$1")"
	ffmpeg -hide_banner -loglevel warning -i "$1" -ss "$2" -c copy "$jas" \
		&& mv "$jas" "$1"
}


if [[ ! -d "$1" ]]; then
	one "$1" "$2"
else
	for i in "$1"/*; do
		one "$i" "$2"
	done
fi
