#!/usr/bin/env bash
set -eo pipefail

out="$2"
if [[ -z "$2" ]]; then # empty
	out="$(exteat <<< "$1")_web.$(extget <<< "$1")"
fi

echo $out
ffmpeg -hide_banner -loglevel warning -i "$1" -preset slow -map 0 -c copy -c:v libx264 -crf 23 -c:a aac -movflags faststart "$out"
