#!/usr/bin/env bash
set -eo pipefail

if [[ "$#" -eq 2 ]]; then
	echo "ERROR: expected exactly 1 arg"
	echo "USAGE: $0 <input directory>"
	exit 1
fi

for i in "$1"/*-1.png; do
	base="$(revcut -d- -f2- <<< "$i")"

	if [[ -f "$base".png ]]; then
		echo "ERROR: not overwriting $base.png"
		continue
	fi

	magick "$base"-*.png -append "$base".png

	touch -r "$i" "$base".png
	rm "$base"-*.png
done
