#!/usr/bin/env bash
set -eo pipefail

if [[ "$#" -ne 1 ]]; then
	echo "ERROR: expected exactly 1 arg"
	echo "USAGE: $0 <input directory>"
	exit 1
fi

for ext in png webp; do
if compgen -G "$1/*-1.$ext" > /dev/null; then

	for i in "$1"/*-1."$ext"; do
		base="$(revcut -d- -f2- <<< "$i")"

		if [[ -f "$base"."$ext" ]]; then
			echo "ERROR: not overwriting $base."$ext""
			continue
		fi

		magick "$base"-*."$ext" -append "$base"."$ext"

		touch -r "$i" "$base"."$ext"
		rm "$base"-*."$ext"
	done

fi
done
