#!/bin/bash
set -euo pipefail

eth="$(nmcli device | awk '$2 == "ethernet" { print $3 == "connected" }' | tr '\n' '+' | sed 's/+$/\n/' | bc)"
wifi="$(nmcli device | awk '$2 == "wifi" { print $3 == "connected" }' | tr '\n' '+' | sed 's/+$/\n/' | bc)"
wifinot="$(nmcli device | awk '$2 == "wifi" { print $3 == "disconnected" }' | tr '\n' '+' | sed 's/+$/\n/' | bc)"

case "$(nmcli networking connectivity)" in
	full)
		if [[ "$eth" -gt 0  && "$wifi" -gt 0 ]]; then
			printf " ⚓️🛜"
		fi
		;;

	limited|none)
		[[ "$wifinot" -gt 0 ]] && printf " 🌊" || printf " ⚓️"
		;;&
	limited)
		printf "◠⏚"
		;;
esac

echo
