#!/bin/bash
set -euo pipefail

if [[ -d /sys/class/power_supply/hidpp_battery_0 ]]; then
	case "$(cat /sys/class/power_supply/hidpp_battery_0/capacity_level)" in
		Critical|Low)
			echo " 🖰🪫"
			;;
	esac
fi
