#!/bin/bash
set -euo pipefail

case "$(swaymsg -t get_inputs | jq -r 'map(select(has("xkb_active_layout_name")))[0].xkb_active_layout_name')" in
	"Estonian (no dead keys)")
		;;
	"Russian (Sweden, phonetic)")
		echo "[ru]"
		;;
	"English (US)")
		echo "[en]"
		;;
	*)
		echo "[kbd?]"
		;;
esac
