#!/bin/bash
set -eu

# Normal mode:
# Print: Clear clip
# Shift: Screenshot region to clip
# Alt: Screenshot to clip
#
# Present mode (Start with Ctrl):
# Print: freeze display (bar will blink green)
# Shift: set screen (not workspace) region

presentpipe="$XDG_RUNTIME_DIR/pipectl.""$(id -u)"".wl-present.pipe"

freezestate="$XDG_RUNTIME_DIR/wl-present-isfrozen"
case "$1" in
	normal)
		if [[ ! -p "$presentpipe" ]]; then
			histNo="$(cliphist list | head -n1 | cut -f1)"
			if [[ ! -e "$XDG_RUNTIME_DIR/cliplast" || "$(cat "$XDG_RUNTIME_DIR/cliplast" 2>&1 || echo 0)" != "$histNo" ]]; then
				wl-copy --clear
				cliphist delete <<< "$histNo"
				cliphist list | head -n1 | cut -f1 > "$XDG_RUNTIME_DIR/cliplast"
			fi

			exit
		fi
	
		if [[ "$(cat "$freezestate")" == 1 ]]; then
			"$(dirname "$0")"/wl-present unfreeze
			echo 0 > "$freezestate"
			exit
		fi

		"$(dirname "$0")"/wl-present freeze
		echo 1 > "$freezestate"
		;;
	shift)
		if [[ -p "$presentpipe" ]]; then
			"$(dirname "$0")"/wl-present set-region
			exit
		fi
		
		pidof -q slurp || grim -g "$(slurp)" - | wl-copy
		;;
	alt)
		grim - | wl-copy #TODO:
		;;
	ctrl)
		if [[ ! -p "$presentpipe" ]]; then
			echo 0 > "$freezestate"
			"$(dirname "$0")"/wl-present mirror
		fi
		;;
	*)
		echo unknown mode
		exit 1
esac
