#!/bin/bash
set -euo pipefail

waydroid session start &
waydroid show-full-ui

swaymsg -t subscribe -m '["window"]' | jq --unbuffered --compact-output |\
while IFS= read -r event; do
	if [[ "$(jq -r '.container.app_id' <<< "$event")" != "Waydroid" ]]; then
		continue
	fi

	if [[ "$(jq -r '.change' <<< "$event")" == "close" ]]; then
		break
	fi

	waydroid prop set persist.waydroid.height "$(jq '.container.window_rect.height' <<< "$event")"
	waydroid prop set persist.waydroid.width "$(jq '.container.window_rect.width' <<< "$event")"
done

waydroid session stop
