#!/usr/bin/env bash
set -eou pipefail

if [ ! -f go.mod ]; then
    echo "go.mod not found, must be at project root!"
    exit 1
fi
if [ -f .github/workflows/golangci-lint.yml ]; then
    echo "golangci-lint.yml already exists!"
    exit 1
fi
if ! git diff --exit-code; then
    echo "git has staged files"
    exit 1
fi
mkdir -p .github/workflows
cat > .github/workflows/golangci-lint.yml << EOF
name: golangci-lint
on:
  push:
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  # https://github.com/golangci/golangci-lint-action
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '>=1.21'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          only-new-issues: true
EOF
git add .github/workflows/golangci-lint.yml
git commit -m'ci: add gh actions golangci-lint'
